title: oscfar
description: OSCFAR (Order Statistic Constant False Alarm Rate) is a radar signal processing technique used for target detection. It adaptively estimates the noise or clutter power in the vicinity of a potential target and sets a detection threshold accordingly, maintaining a constant false alarm rate regardless of the background noise characteristics.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  GitHub: https://github.com/Chujo58/oscfar
  PyPi: https://pypi.org/project/oscfar
